/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2017-01-06 11:01:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class SignUp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/page/../head.jsp", Long.valueOf(1483699701823L));
    _jspx_dependants.put("/WEB-INF/taglibs.jsp", Long.valueOf(1483699701830L));
    _jspx_dependants.put("/WEB-INF/page/../style/style_signUp.jsp", Long.valueOf(1483699762321L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("   <!-- Head -->\r\n");
      out.write("   <head>\r\n");
      out.write("   \t\t");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"author\" content=\"Fontanet Nicolas\" lang=\"fr\"/>\r\n");
      out.write("<title>Projet AREA</title>\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" />");
      out.write("\r\n");
      out.write("   \t\t");
      out.write("<style>\r\n");
      out.write("/*---- html ----*/\r\n");
      out.write("html  /* Balise html*/\r\n");
      out.write("{\r\n");
      out.write("\toverflow-y: scroll;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*---- boby ----*/\r\n");
      out.write("body /*Balise body*/\r\n");
      out.write("{\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\tbackground-image: url(\"https://images.alphacoders.com/176/thumb-1920-176261.jpg\");\r\n");
      out.write("\tbackground-repeat: no-repeat;\r\n");
      out.write("\tbackground-attachment: fixed;\r\n");
      out.write("\tfont-family: 'Titillium Web', sans-serif;\r\n");
      out.write("  \t-webkit-background-size: cover; /* pour anciens Chrome et Safari */\r\n");
      out.write("  \tbackground-size: cover; /* version standardisée */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*--- Balise H1 ---*/\r\n");
      out.write("h1\r\n");
      out.write("{\r\n");
      out.write(" \ttext-align: center;\r\n");
      out.write(" \tcolor: white;\r\n");
      out.write(" \tfont-weight: 30px;\r\n");
      out.write(" \tmargin: 0 0 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ---- Balise lien_enregistre ----*/\r\n");
      out.write(".lien_enregistre\r\n");
      out.write("{\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\t-webkit-transition: .5s ease;\r\n");
      out.write("\ttransition: .5s ease;\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".erreur\r\n");
      out.write("{\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor: #ff0066;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Div avec class= div_formulaire*/\r\n");
      out.write(".div_formulaire\r\n");
      out.write("{\r\n");
      out.write("\twidth: 500px;\r\n");
      out.write("\theight: 600px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tbackground-color: rgba(52, 73, 94, 0.7);\r\n");
      out.write("\tborder-raduis: 4px;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("\tmargin-top: 150px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Div avec class= form_container*/\r\n");
      out.write(".div_container\r\n");
      out.write("{\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Div avec class= div_logo*/\r\n");
      out.write(".div_logo img\r\n");
      out.write("{\r\n");
      out.write("    width: 230px;\t\r\n");
      out.write("\theight: 100px;\r\n");
      out.write("\tmargin-top: -60px;\r\n");
      out.write("\tmargin-bottom: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Div avec class=input_text*/\r\n");
      out.write(".input_text\r\n");
      out.write("{\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("\tmargin-bottom: 20px;\r\n");
      out.write("\tbackground-color: #fff;\r\n");
      out.write("\tpadding-left: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Div avec class=util */\r\n");
      out.write(".util\r\n");
      out.write("{\r\n");
      out.write("\tbackground-image: url(\"http://us.123rf.com/450wm/richcat/richcat1112/richcat111200002/11479160-illustration-graphique-de-l-homme-en-costume-d-affaires-comme-icone-d-utilisateur-avatar.jpg\");\r\n");
      out.write("\tbackground-repeat: no-repeat;\r\n");
      out.write("\tbackground-repeat: 20px 20px;\r\n");
      out.write("\tbackground-size: 25px;\r\n");
      out.write("\tpadding-left: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Div avec class=mail */\r\n");
      out.write(".mail\r\n");
      out.write("{\r\n");
      out.write("\tbackground-image: url(\"http://www.icone-png.com/png/54/53711.png\");\r\n");
      out.write("\tbackground-repeat: no-repeat;\r\n");
      out.write("\tbackground-position: 5px 10px;\r\n");
      out.write("\tbackground-size: 20px;\r\n");
      out.write("\tpadding-left: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Div avec class=pass */\r\n");
      out.write(".pass\r\n");
      out.write("{\r\n");
      out.write("\tbackground-image: url(\"http://www.pngfactory.net/_png/_thumb/20638-bubka-Security.png\");\r\n");
      out.write("\tbackground-repeat: no-repeat;\r\n");
      out.write("\tbackground-position: 5px 10px;\r\n");
      out.write("\tbackground-size: 20px;\r\n");
      out.write("\tpadding-left: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Div avec class=bouton_submit */\r\n");
      out.write(".bouton_submit\r\n");
      out.write("{\r\n");
      out.write(" \tpadding: 20px 40px;\r\n");
      out.write(" \tmargin-left: auto;\r\n");
      out.write(" \tmargin-right: auto;\r\n");
      out.write(" \tcolor: #fff;\r\n");
      out.write(" \tborder-radius: 4px;\r\n");
      out.write(" \tborder: none;\r\n");
      out.write(" \tbackground-color: #1ab188;\r\n");
      out.write(" \tdisplay: block;\r\n");
      out.write(" \t\r\n");
      out.write(" \ttext-transform: uppercase;\r\n");
      out.write(" \tfont-size: 2rem;\r\n");
      out.write(" \tfont-weight: 600;\r\n");
      out.write(" \tletter-spacing: .1em;\r\n");
      out.write(" \t-webkit-transition: all 0.5s ease;\r\n");
      out.write(" \ttransition: all 0.5s ease;\r\n");
      out.write(" \t-webkit-appearance: none;\r\n");
      out.write(" \toutline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Div avec class=bouton_submit sur le hover et le focus */\r\n");
      out.write(".bouton_submit:hover, .bouton_submit:focus\r\n");
      out.write("{\r\n");
      out.write("\tbackground: #179b77;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>");
      out.write("\r\n");
      out.write("   \t\t<!-- <link type=\"text/css\" rel=\"stylesheet\" href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\"/> -->\r\n");
      out.write("   </head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<div class=\"div_formulaire\">\r\n");
      out.write("\t\t\t<div class=\"div_logo\">\r\n");
      out.write("\t\t\t\t<img class=\"logo\" src=\"https://upload.wikimedia.org/wikipedia/fr/thumb/b/bb/AREA.svg/727px-AREA.svg.png\" width=\"auto\" height=\"auto\" alt=\"logo\"/>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<h1> Enregistrement </h1>\r\n");
      out.write("\t\t\t<div class=\"form_container\">\r\n");
      out.write("\t\t\t<!-- Formulaire -->\r\n");
      out.write("\t\t\t\t<form class=\"signUp\" method=\"post\" action=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"top-row\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"nom\" name=\"nom\" type=\"text\" placeholder=\"Nom\" class=\"input_text util\"/>\r\n");
      out.write("\t\t\t\t\t\t<input id=\"prenom\" name=\"prenom\" type=\"text\" placeholder=\"Prenom\" class=\"input_text util\"/><br/>\r\n");
      out.write("\t\t\t\t\t</div> <!-- !top-row -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"top-row\">\r\n");
      out.write("\t\t\t\t\t<input id=\"email\" name=\"email\" type=\"email\" placeholder=\"Mail\" class=\"input_text mail\"/><br/>\r\n");
      out.write("\t\t\t\t\t</div> <!-- !top-row -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"top-row\">\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<input id=\"pass\" name=\"pass\" type=\"password\" placeholder=\"Mot de passe\" maxlength=\"8\" class=\"input_text pass\"/><br/>\r\n");
      out.write("\t\t\t\t\t</div> <!-- !top-row -->\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<input class=\"bouton_submit\" type=\"submit\" value=\"Enregister !\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div> <!-- !form_container -->\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\t<!-- !div_fromulaire  -->\t  \r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/page/../head.jsp(4,40) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("http://icons.iconarchive.com/icons/iconsmind/outline/128/Ruler-2-icon.png");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/page/SignUp.jsp(7,55) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/css/style_signUp.css");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /WEB-INF/page/SignUp.jsp(17,47) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/signUp");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/page/SignUp.jsp(32,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${erreur}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<p class=\"erreur\"> ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write(" </p>\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    }
    return false;
  }
}
